ARG BUILD_FROM=ghcr.io/hassio-addons/base:13.0.0
FROM ${BUILD_FROM}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

WORKDIR /tmp

#RUN wget "https://powerwalker.com/wp-content/uploads/2022/01/pmp105_linux64.zip" -O "pm.zip"
#RUN unzip pm.zip


# apt install libhidapi-libusb0
# pip3 install hid
# /dev/bus/usb/002/009

# https://powerwalker.com/wp-content/uploads/2022/01/pmp105_linux64.zip