---
channel: stable
addons:
  ffserver:
    repository: norskfjellgeit/ha-ffserver
    target: ffserver
    image: docker.io/norskfjellgeit/ha-ffserver
# NOTE! Work in progress
#  powerwalker_ups:
#    repository: norskfjellgeit/ha-powerwalker
#    target: powerwalker_ups
#    image: docker.io/norskfjellgeit/ha-powerwalker
